version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backnd:
    build: ./backnd
    container_name: backnd
    ports:
      - "9000:9000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/ecommerce
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backnd

volumes:
  mongo-data: