# --- STAGE 1: Build the application ---
#Base image with Node.js 18. This is the first stage called builder
FROM node:18-alpine AS builder
#Set the working directory inside the container to /app.
WORKDIR /app

# Copy package.json and package-lock.json to the container.
COPY package*.json ./
# Install all node.js dependencies
RUN npm install

# --- STAGE 2: Production Image ---
# Start a new, clean Node.js image for the final app.
FROM node:18-alpine
#Set the working directory to /app again.
WORKDIR /app

#Copy installed dependencies from the builder stage.
COPY --from=builder /app/node_modules ./node_modules
#Copy package.json files to the final image.
COPY package*.json ./

#Copy all the app files to the container.
COPY . .

# Expose the port your server will run on (e.g., 9000)
EXPOSE 9000

# Command to run the application Start the app by running node server.js
CMD [ "node", "server.js" ]


