# Backend Dockerfile
FROM node:18.9.1

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy rest of the files
COPY . .

# Expose port
EXPOSE 9000

# Run backend dev server
CMD ["npm", "run", "dev"]
